services:
  reload-server:
    container_name: reload-server
    build:
      context: .
      dockerfile: ./dev-server/reload-server.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - dev
    develop:
      watch:
        - action: sync+restart
          path: reload-server.js
          target: /reload-server/reload-server.js

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dev-server/nginx.Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/certs:ro
    networks:
      - dev
    develop:
      watch:
        - action: sync+restart
          path: nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
        - action: sync+exec 
          path: ./../../app
          target: /simplebooknook
          ignore:
            - src/
          exec:
            command: ["./send-reload.sh"]
          
networks:
  dev:
    name: dev
